import {StyleSheet} from 'react-native';

export default StyleSheet.create({
  container: {
    flex: 1,
    display: 'flex',
    flexDirection: 'column',
    backgroundColor: '#FFFFFF',
    justifyContent: 'center',
    color: '#fff',
    borderTopRightRadius: 25,
    borderTopLeftRadius: 25,
    borderWidth: 0.5,
    borderStyle: 'solid',
    overflow: 'hidden',
  },
  title: {
    fontSize: 20,
    textAlign: 'center',
    marginBottom: 8,
  },
  buttonsContainer: {
    display: 'flex',
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-start',
    marginLeft: 30,
    marginRight: 30,
    position: 'absolute',
    top: 30,
  },
  button: {
    display: 'flex',
    justifyContent: 'flex-start',
    backgroundColor: '#21A1FD',
    marginLeft: 40,
    marginRight: 40,
    width: 60,
    height: 60,
    borderRadius: 30,
  },
  medicationsContainer: {
    flex: 8,
    display: 'flex',
    flexDirection: 'column',
    marginTop: 120,
  },
  listHeaderContainer: {
    height: 35,
    display: 'flex',
    flexDirection: 'row',
    backgroundColor: '#21A1FD',
  },
  listRowContainer: {
    height: 60,
    display: 'flex',
    flexDirection: 'row',
    backgroundColor: 'white',
    borderBottomWidth: 0.6,
    borderColor: '#21A1FD',
  },
  headerEntry: {
    flex: 1,
    display: 'flex',
    justifyContent: 'center',
    width: '25%',
  },
  rowEntry: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    width: '25%',
  },
  headerText: {
    textAlign: 'center',
    fontSize: 18,
  },
  entryText: {
    textAlign: 'center',
    fontSize: 16,
  },
});
