import {StyleSheet} from 'react-native';

export default StyleSheet.create({
  container: {
    flex: 1,
    display: 'flex',
    flexDirection: 'column',
    backgroundColor: '#FFFFFF',
    justifyContent: 'center',
    color: '#fff',
    borderTopRightRadius: 25,
    borderTopLeftRadius: 25,
    borderWidth: 0.5,
    borderStyle: 'solid',
    overflow: 'hidden',
  },
  inputContainer: {
    width: 240,
    flex: 1,
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'baseline',
    alignSelf: 'center',
  },
  title: {
    flex: 1.5,
    fontSize: 30,
    lineHeight: 44,
    color: 'black',
    alignItems: 'center',
    alignSelf: 'center',
    textAlign: 'center',
    justifyContent: 'flex-end',
    top: 60,
  },
  heading: {
    fontSize: 24,
    color: 'black',
    alignItems: 'center',
    alignSelf: 'center',
    textAlign: 'center',
    justifyContent: 'flex-end',
  },
  numberInput: {
    borderBottomWidth: 1,
    borderColor: '#777',
    width: 120,
    fontSize: 40,
    textAlign: 'center',
  },
  unitInputContainer: {
    width: 120,
    height: 60,
    alignSelf: 'flex-end',
  },
  unitInput: {
    borderTopWidth: 0,
    borderLeftWidth: 0,
    borderRightWidth: 0,
    borderBottomWidth: 1,
    borderBottomColor: '#777',
    fontSize: 18,
    textAlign: 'center',
    padding: 10,
    margin: 15,
  },
  buttonContainer: {
    flex: 0.5,
    justifyContent: 'center',
  },
});
